### DISCUSSION TITLE
patronictl edit-config & pg_hba

### DISCUSSION THREAD

**Discussion by kkrasnov1** [autobase-tech/autobase#116] [Q&A] [answered]
Hi,

The /etc/patroni/patroni.yml doesn't contain the current configuration pg_hba after executing deploy_pgcluster.yml.
patronictl edit-config will erase pg_hba.conf. How do I correctly change use patronictl edit-config command?

**Comment by vitabaks** [comment, marked as answer]
I have not yet transferred the pg_hba.conf management to the Patroni.

**Reply by vitabaks** [reply]
If you need to change pg_hba. conf, you can change the postgresql_pg_hba variables in vars/main.yml and run the playbook with the tag:
`ansible-playbook deploy_pgcluster.yml --tag pg_hba`

**Reply by kkrasnov1** [reply]
Thank you.

When do you plan to transfer the pg_hba.conf management to the Patroni?

**Reply by vitabaks** [reply]
I haven't seen the need for this yet, but I will think about this possibility.

**Comment by vitabaks** [comment]
Here is an example for `bootstrap.dcs.postrgesql.pg_hba`

patronictl edit-config

```
postgresql:
  parameters:
    ...
  pg_hba:
    - local all all trust
    - host all all localhost trust
    - host all all 0.0.0.0/0 md5
    - host replication replicator localhost trust
    - host replication replicator 0.0.0.0/0 md5
```
