### DISCUSSION TITLE
pgbouncer service is disabled on Debian

### DISCUSSION THREAD

**Discussion by Valentin-Chip** [autobase-tech/autobase#146] [General]
Service pgbouncer is not enabled on Debian based OS :
```
- name: Stop and disable standard init script
  service:
    name: pgbouncer
    state: stopped
    enabled: false
  when: ansible_os_family == "Debian"
  tags: pgbouncer_service, pgbouncer
```
It's bug?
