### DISCUSSION TITLE
WAL-G: Create daily backup

### DISCUSSION THREAD

**Discussion by fatmaAliGamal** [autobase-tech/autobase#392] [General]
```
cron_jobs: 
# Example for walg
 - name: "WAL-G: Create daily backup"
   user: "postgres"
   file: /etc/cron.d/walg
   minute: "55"
   hour: "16"
   day: "*"
   month: "*"
   weekday: "*"
   job: "[ $(curl -s -o /dev/null -w '%{http_code}' http://{{ inventory_hostname }}:{{ patroni_restapi_port }}) = '200' ] && wal-g backup-push"
```
-----------------------------
```
# WAL-G
wal_g_install: true  # or 'true'
wal_g_version: "2.0.1"
wal_g_json:  # config https://github.com/wal-g/wal-g#configuration
  - { option: "AWS_ACCESS_KEY_ID", value: "{{AWS_ACCESS_KEY_ID}}" }
  - { option: "AWS_SECRET_ACCESS_KEY", value: "{{AWS_SECRET_ACCESS_KEY}}" }
  - { option: "WALG_S3_PREFIX", value: "{{WALG_S3_PREFIX}}" }
  - { option: "AWS_S3_FORCE_PATH_STYLE", value: "true" }
  - { option: "WALG_COMPRESSION_METHOD", value: "gzip" } #"lz4", "zstd", "brotli", "gzip",
  - { option: "PGDATA", value: "{{ postgresql_data_dir }}" }
  - { option: "PGHOST", value: "{{ postgresql_unix_socket_dir }}" }

wal_g_patroni_cluster_bootstrap_command: "wal-g backup-fetch {{ postgresql_data_dir }} LATEST"
```

-----------------------------------------
```
# https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#bootstrap
patroni_cluster_bootstrap_method: "initdb"  # or "wal-g", "pgbackrest", "pg_probackup","initdb"

# https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#building-replicas
patroni_create_replica_methods:
#  - pgbackrest
  - wal_g
#  - pg_probackup
  - basebackup

```
----------------------------------------------------
 at postgresql_parameters:

```
  - { option: "archive_command", value: "wal-g wal-push %p" }  # archive WAL-s using WAL-G
```
---------------------------
change location of 
```
# PostgreSQL variables
postgresql_version: "15"
postgresql_data_dir: "/dev/xvdb/{{ postgresql_version }}/{{ postgresql_cluster_name }}"
```
why did not take backup to s3 

i run `ansible-playbook deploy_pgcluster.yml   -e "enable_timescale=true" -e "AWS_ACCESS_KEY_ID=*****" -e "AWS_SECRET_ACCESS_KEY=******" -e "WALG_S3_PREFIX=s3://soa-backup/soabackup/"`
