### DISCUSSION TITLE
Add firewall_type variable to implement other types fw, firewalld in this case

### DISCUSSION THREAD

**Discussion by redy01** [autobase-tech/autobase#501] [Ideas]
Quick implementation of firewalld.
rename: roles/ansible-role-firewall to roles/fw_iptables
create role: roles/fw_firewalld
with two tasks in tasks/main.yml
```
- name: Ensure firewalld is present.
  ansible.builtin.package:
    name: firewalld
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3

- name: Configure the firewall service.
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    immediate: true
    permanent: true
    state: enabled
  with_items: "{{ firewall_allowed_tcp_ports }}"

```

new variable is needed in vars/system.yml
```
firewall_type: "firewalld" # available 'iptables','firewalld'
```
replace "role: ansible-role-firewall" with role: "fw_{{ firewall_type }}" in files:
./add_balancer.yml
./add_pgnode.yml
./balancers.yml
./config_pgcluster.yml
./consul.yml
./deploy_pgcluster.yml
./etcd_cluster.yml

in bash
`for _file in $(ls *.yml); do sed -i 's/ansible-role-firewall/"fw_{{ firewall_type }}"/g' $_file; done`

Last operation is to install correct firewall package in deploy_pgcluster.yml
replace tasks:
```
    - name: Make sure that the firewall is installed
      ansible.builtin.package:
        name: "{{ firewall_type }}"
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: ansible_os_family == "RedHat"

    - name: Make sure that the iproute is installed
      ansible.builtin.apt:
        name: "iproute2"
        state: present
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      when: ansible_os_family == "Debian"

```
with tasks:
```
    - name: Make sure that the {{ firewall_type }} is installed
      ansible.builtin.package:
        name: "{{ firewall_type }}"
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: ansible_os_family == "RedHat"

    - name: Make sure that the {{ firewall_type }} is installed
      ansible.builtin.apt:
        name: "{% if firewall_type == 'iproute' %}iproute2{% else %}{{firewall_type}}{% endif %}"
        state: present
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      when: ansible_os_family == "Debian"
```
