### DISCUSSION TITLE
node reboot on kernel and security patches

### DISCUSSION THREAD

**Discussion by chuegel** [autobase-tech/autobase#509] [Ideas]
In our environment (PCIDSS) we are required to reboot all linux hosts when a new kernel/security patch is installed.
Right now, the `update_pgcluster.yml -e target=system` playbook doesn't take this into consideration.
I'm not sure if this is worth a PR or not but I thought I give it a try.

However, when adding this code to `roles/update/tasks/system.yml`
```
- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required
  changed_when: reboot_required.stat.exists
  when: ansible_os_family == "Debian"
  notify: "reboot host"

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers
```
` cat roles/update/handlers/main.yml`

```
---

- name: Rebooting host
  ansible.builtin.reboot:
    reboot_timeout: 600
    test_command: uptime
  listen: "reboot host"
```
The handler runs multiple times and I don't understand why?

```
TASK [update : Check if a reboot is required.] ***********************************************************************************************************************************************************************************************
changed: [192.168.100.75]

RUNNING HANDLER [update : Rebooting host] ****************************************************************************************************************************************************************************************************
changed: [192.168.100.75]

RUNNING HANDLER [update : Rebooting host] ****************************************************************************************************************************************************************************************************
changed: [192.168.100.75]

RUNNING HANDLER [update : Rebooting host] ****************************************************************************************************************************************************************************************************
changed: [192.168.100.75]

RUNNING HANDLER [update : Rebooting host] ****************************************************************************************************************************************************************************************************
changed: [192.168.100.75]

TASK [Start Services] ************************************************************************************************************************************************************************************************************************

TASK [update : Start Patroni service] ********************************************************************************************************************************************************************************************************
ok: [192.168.100.75]
```
Any hints are much appreciated.

Cheers
