### DISCUSSION TITLE
SUDO configuration

### DISCUSSION THREAD

**Discussion by redy01** [autobase-tech/autobase#514] [General]
Hi, Just wonder where/ for what postgres user need sudo access?
default vars/system.yml
```
sudo_users:
  - name: "postgres"
    nopasswd: "yes"  # or "no" to require a password
    commands: "ALL"
```
