### DISCUSSION TITLE
Usage of postgresql_cluster playbooks in an existing repository

### DISCUSSION THREAD

**Discussion by amenophis** [autobase-tech/autobase#677] [Q&A]
Hi @vitabaks,

We are currently trying to use your playbooks from our own ansible internal project.

It seems your project is not designed in this way, you recommend to use it from a clone directly.

You can see below how we managed to use it, but it is not really user firendly ...
You can see variables can't be overrided while importing a playbook, the only way is to define facts.

Do you have some advises or recommendations to provide to use your playbooks inside our own project ?

```yaml
---

- name: Override variables from pgcluster playbook
  hosts: all
  pre_tasks:
    - name: Set Facts - Root variables
      ansible.builtin.set_fact:
        postgresql_cluster_name: main
        postgresql_version: 13
        patroni_cluster_name: 'postgres-cluster'
        patroni_install_version: "3.3.1"

    - name: Set Facts - Composed variables
      ansible.builtin.set_fact:
        postgresql_data_dir: "/var/local/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_name }}"

    - name: Set Facts - Remove Cluster
      ansible.builtin.set_fact:
        remove_postgres: true
        remove_etcd: true
      when: target == 'remove_cluster'

- name: Run playbook
  ansible.builtin.import_playbook: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/roles/vitabaks.postgresql_cluster/{{ target }}.yml"
```

We are able to run the playbook with the following command (we can choose the playbook to run by changing the target (ex: `config_pgcluster`)):

```bash
ansible-playbook -i inventories/poc/hosts.yml playbooks/postgresql_cluster/main.yml -e target='config_pgcluster'
```

Thanks :pray:
