### DISCUSSION TITLE
arm support

### DISCUSSION THREAD

**Discussion by arenddeboer** [autobase-tech/autobase#866] [Ideas]
I was deploying a cluster in a mixed arm/x86 environment and realized arm support is partly implemented.
For instance, the Consul playbook seems to look at the architecture and download binaries based on an architecture map.
When standing up a self-hosted cluster with just etcd, the only roadblock seems to be downloading the correct etcd binary which I was able to get working by retrofitting "consul_architecture_map" from ```roles/consul/defaults/main.yml```  into :

```
etcd_architecture_map:
  # this first entry seems redundant
  # (but it's required for reasons)
  amd64: amd64
  x86_64: amd64
  # todo: arm32 / armelv5
  armv6l: armhfv6
  armv7l: armhfv6
  aarch64: arm64
  # Used by Apple Silicon Macs
  arm64: arm64
  32-bit: "386"
  64-bit: amd64

# Extra packages
etcd_package_repo: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-{{ etcd_architecture_map[ansible_architecture] }}.tar.gz"
```
(```vars/Debian.yml``` )

I can create a PR if there is interest in accepting this change. Of course a lot more is needed to fully support the arm architecture, but it's another step in this direction.
